default: &default
  adapter: mysql2
  encoding: utf8
  database: smcb
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
