default: &default
  adapter: mysql2
  encoding: utf8
  database: smcb
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
