name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Docker Composeのインストール
    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    # Docker Composeでサービスを起動
    - name: Build and start containers
      run: docker-compose up -d

    # MySQLが起動するまで待機 (MySQLのヘルスチェック)
    - name: Wait for MySQL to be ready
      run: |
        while ! docker-compose exec db mysqladmin ping -h localhost --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    # Railsアプリケーションのテストを実行
    - name: Run tests
      run: |
        docker-compose exec app bin/rails db:create db:schema:load
        docker-compose exec app bin/rails test
